### ISSUE TITLE
GSL

### ISSUE THREAD

**Issue by shadowwalkersb** [cryoem/eman2-feedstock#1]
Windows build of GSL is worked on https://github.com/conda-forge/gsl-feedstock/pull/11. Until that PR is finished we can use [salilab](https://anaconda.org/salilab/gsl) channel which hosts v1.16.

**Comment by shadowwalkersb** [comment]
GSL build for Windows on conda-forge might not get finalized any time soon. @sludtke42 , is it acceptable to use v1.16 from salilab for eman's Windows builds? Or, we can pull from https://github.com/ampl/gsl? They seem to support v2.1 and have cmake support. Could be easier to fix things with them and ask for help if needed.

**Comment by sludtke42** [comment]
GSL is difficult to build for windows ?   That seems odd. It should be a pretty standard library...

Can you clarify now what compiler tools conda-forge uses for Windows?

**Comment by shadowwalkersb** [comment]
Visual Studio.

**Comment by shadowwalkersb** [comment]
How is GSL built in the current build system?

**Comment by sludtke42** [comment]
Visual Studio I believe. Vernon is really the one to ask about the current Windows builds.

**Comment by shadowwalkersb** [comment]
GSL for Windows is now available on conda-forge. 🎉

**Comment by sludtke42** [comment]
👍
